name: Update Stream Status

permissions:
  contents: write

on:
  schedule:
    # ── 1日中 1 時間毎
  #  - cron: '0 * * * *'
    # ── 1日中 15 分毎
  #  - cron:  '*/15 * * * *'
    # ── JST 15:00～0:30（UTC 6～15）を 15 分毎
  #  - cron: '0,15 6-15 * * *'
    # ── JST 1:00（UTC 16）を 1 回だけ（30分間隔には含めない）
  #  - cron: '0 16 * * *'
    # ── 残りの時間帯（JST 2:00～16:59 → UTC 17～23,0～7）を 1 時間毎
    - cron: '*/15 0-5,16-23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Fetch stream data & generate site
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
        run: npm run fetch

      - name: Commit & push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add docs/**
          git commit -m "自動更新: $(date -u '+%Y-%m-%d %H:%M')" || echo "No changes"
          git push
